spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate=INFO
jwt.secret=R4iIU+F86NT4Zmht4UMb3VH27Y8ZJBSpGG4V3ih0YT24Plo0FfNb+lykBLcBmXpwCsfHJFL1a/uYmOPIyp0kiQ==
jwt.expiration=86400
spring.jpa.hibernate.ddl-auto=update
axon.eventhandling.mode=simple
axon.eventhandling.simple.event-bus=simpleEventBus
axon.eventhandling.simple.command-bus=simpleCommandBus
axon.eventhandling.simple.query-bus=simpleQueryBus
axon.axonserver.enabled=false
app.splitwise.api.url=https://secure.splitwise.com/api/v3.0
app.splitwise.api.key=